name: www_hw4
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - python-telegram-bot
  - sqlalchemy
  - flask
  - python-dotenv
  - flask-sqlalchemy
  - requests
  - psycopg2
  - sqlalchemy-utils
  - flask-login
  - flask-cors
